config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'categories/index'
  get 'categories/edit'
  get 'categories/new'
  get 'categories/show'
  get 'home/index'
  root  'home#index'
  resources :posts
  resources :categories

  get '/about', :to => 'pages#about'
  get '/contact', :to => 'pages#contact'
  get '/resources', :to => 'pages#resources'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable,  :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached :image
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :posts

  def to_s
    name
  end
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :posts
  # validates :name, presence: true
  # attr_accessor :category_type
  # has_many :posts, -> { order(:name) }, :dependent => :destroy, :class_name => 'Category'

  has_and_belongs_to_many  :posts

  def to_s
    name
  end
end

app/models/gategory.rb
class Gategory < ApplicationRecord
  def category_params
    params.require(:qategory).permit(:name)
  end
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true
  validates :title, :uniqueness => true
  validates :title, :length => { :maximum => 65}

  has_and_belongs_to_many  :categories
  belongs_to :author

  has_one_attached :image



  scope :published, ->{ where.not(published_at: nil) }
  scope :unpublished, ->{ where(published_at: nil) }

  def to_s
    title
  end
  def post_parms
    	params.require(:post).permit(:title, :body, :category_id, :author_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name )
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # code
  end
  private
  def home_params
    params.require(:home).permit(:image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    # code
  end

  def contact
    # code
  end

  def resources
    # code
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		# @posts = Post.all.order('created_at DESC')
		# @post = Post.published
		@posts = Post.all
		@categories = Category.all
	end

  def create
		@posts = Post.new(post_params)
		if @post.save
			redirect_to posts_path
		else
			render "new"
		end
  end

	def new
	  @post = Post.new
	end

	def edit
	  @post = Post.find(params[:id])
	end

	def show
		@post = Post.find(params[:id])
		@posts = Post.order("created_at desc").limit(4).offset(1)
	end

  def update
    @post = Post.find(params[:id])
		if @post.update_attributes(post_params)
			redirect_to posts_path
		else
			render "edit"
		end
  end

	def destroy
	  @post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body, :image, :category_id, :author_id)
		end
end

# https://github.com/MMagdys/Blog/blob/master/app/admin/dashboard.rb#L5

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Categories</h1>


    <% @categories.each do |category| %>

      <li><%= link_to category.name, category %></li>


    <% end %>

</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1><strong><%= @category.name %> Posts</strong></h1>

<% if @posts.each do |post| %>
	<div class="jumbotron" style="margin-bottom: 10px;">
			<h3><%= link_to post.title, post%></h3>
			<p class="lead"><%= post.body%></p>
		</div>

<% end.empty? %>
	<p>Sorry, There is no post here!</p>
<% end %>

<hr>
<%= link_to 'All Categories', categories_path %>

app/views/layouts/_navbar.html.erb
<html>
<head>
	<title>Dashboard</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="assets/stylesheets/css/style.css">
</head>
<body>
	<input type="checkbox" id="checkbox">
	<header class="header">
		<h2 class="u-name">BLOGGER <b>BAR</b>
			<label for="checkbox">
				<i id="navbtn" class="fa fa-bars" aria-hidden="true"></i>
			</label>
		</h2>
		<i class="fa fa-user" aria-hidden="true"></i>
	</header>
	<div class="body">
		<nav class="side-bar">
			<div class="user-p">
				<%= link_to  image_tag('black.png'), root_path, class: "side-bar" %>
				<%= link_to  image_tag('black.png'), root_path, class: "side-bar" %>
			 <!-- <img alt="Blogger Logo" src="images/black.png" class="user-image" /> -->
				<h4>Nonanik</h4>
			</div>
			<ul>
				<li>
					<a class="bi bi-calendar3" href="<%= about_path %>">
					<i class="bi bi-calendar3"  aria-hidden="true"></i>
					<span>Kategroiler</span>
          </a>
				</li>
				<li>
					<a href="#">

						<i class="fa fa-desktop" aria-hidden="true"></i>
						<span>Dashboard</span>
					</a>
				</li>
				<li>
					<a href="#">
						<i class="fa fa-envelope-o" aria-hidden="true"></i>
						<span>Message</span>
					</a>
				</li>
				<li>
					<a href="#">
						<i class="fa fa-comment-o" aria-hidden="true"></i>
						<span>Comment</span>
					</a>
				</li>
				<li>
					<a href="#">
						<i class="fa fa-info-circle" aria-hidden="true"></i>
						<span>About</span>
					</a>
				</li>
				<li>
					<a href="#">
						<i class="w3-dropdown-click w3-button w3-bar-item topnav-icons fa fa-menu" aria-hidden="true" href="<%= posts_path%>"></i>
						<span>Kategroiler</span>
					</a>
				</li>
				<br>
				<li>
					<a href="#">
						<i class="fa fa-power-off" type="button" id="cancel-edit" value="cancel" aria-hidden="true"></i>
						<span>Logout</span>
					</a>
				</li>
			</ul>
		</nav>

</div>
		<script type="text/javascript">
		$(document).ready(function(){
			$(".sidebar-btn").click(function(){
				$(".wrapper").toggleClass("collapse");
			});
		});


		$("#cancel-edit").click(function(){
			window.open('','-parent','');
			window.close()
		});
		</script>

	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <%= javascript_importmap_tags %>

  </head>

  <body>

    <%= render "layouts/navbar" %>
<%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/resources.html.erb
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %> <br/>
		<%= f.text_field :title %> <br/>
	</p>

	<p>
		<%= f.label :body %> <br/>
		<%= f.text_area :body %> <br/>
	</p>

	<p>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %> <br/>
	</p>

	<p>
		<%= f.submit "Update Post" %> <br/>
	</p>

<% end %>
<%= link_to "Go back", post_path  %>

app/views/posts/index.html.erb
<!-- <h1>Blog posts</h1> -->
<div class="row">
	<div class="col-md-8">
		<% @posts.each do |post| %>
		<div class="jumbotron" style="margin-bottom: 10px;">
			<h3><%= link_to post.title, post%></h3>
			<span class="badge badge-pill badge-secondary"><%=  post.category.name%></span>
			<br><br>
			<p class="lead"><%= post.body%></p>
		</div>
	<% end %>

	</div>

	<div class="col-md-4">
		<h4>Categories</h4>
		<div class="list-group">
			<% @categories.each do |category| %>
				 <a href="<%= category_path(:id => category.id) %>" class="list-group-item list-group-item-action">
		    <%= category.name %>
		  </a>

			<% end %>


		 <!--  <a href="#" class="list-group-item list-group-item-action active">
		    Cras justo odio
		  </a>
		  <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in
		  </a>
		  <a href="#" class="list-group-item list-group-item-action">Morbi leo risus
		  </a> -->

		</div>
	</div>
</div>

app/views/posts/new.html.erb
<h1>Add New Post</h1>
<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %> <br/>
		<%= f.text_field :title %> <br/>
	</p>

	<p>
		<%= f.label :body %> <br/>
		<%= f.text_area :body %> <br/>
	</p>

	<p>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %> <br/>
	</p>

	<p>
		<%= f.submit "Add Post" %> <br/>
	</p>

<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.title%> </h1>
<p><%= @post.created_at.strftime("%b %d. %Y") %></p>

<p><%= @post.body %></p>
<br>
<p><strong>Category: </strong> <%= link_to @post.category.name, category_path(:id => @post.category.id) %></p>

<hr>
<%= link_to "All Posts", posts_path %>